import {FieldTypeInFunction} from "../../metadata-builder/metadata/FieldMetadata";

export class WrongAutoGeneratedIdFieldTypeError extends Error {
    name = "WrongAutoGeneratedIdFieldTypeError";

    constructor(document: any, whichProperty: string, type: Function|string) {
        super();
        this.message = "Id auto generation is set for " + whichProperty + " in the " + JSON.stringify(document)
            + ", but wrong field type " + type + " is set. Only strings are supported for auto generated ids";
    }

}